
esphome:
  name: boilercontrol2
  friendly_name: Boilercontrol2
  build_path: /home/minty/Documents/BoilerControl/SRC/build
  includes:
   - my_components/HD44780/HD44780.cpp
   - my_components/HD44780/HD44780.h
   - my_components/ESP32-MAX31865/include/Max31865.h
   - my_components/ESP32-MAX31865/src/Max31865.cpp
   - my_components/ESP32-MAX31865/src/numerics.cpp
   - my_components/OneWireNg/src/platform/OneWireNg_ArduinoIdfESP32.h
   - my_components/OneWireNg/src/OneWireNg_CurrentPlatform.h
  platformio_options:
    board_build.flash_mode: dio
    upload_protocol: esptool
    debug_tool: esp-builtin
    platform_packages: 
      - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
      - framework-espidf @ 3.40405.230623
    build_flags:
     - -DCONFIG_OVERDRIVE_ENABLED
     - -DCONFIG_CRC16_ENABLED
     - -DCONFIG_ITERATION_RETRIES=1
     - -DOWNG_NO_NATIVE_CONFIG
#     - -DCONFIG_PWR_CTRL_ENABLED

esp32:
  #board: esp32-c3-devkitm-1
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: esp-idf


 
#external_components:
# - source:
#      type: local
#      path: ./boilercontrol

    

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG


external_components:
#  - source:
#      type: git
#      url: https://github.com/LucasCanete/HD44780-ESP-IDF-CPP.git
#    components: [components]
  - source:
      type: local
      path: my_components
    components: [boilercontrol]


sensor:
  - platform: boilercontrol
    temperature_boiler:
      name: "Boiler"
    temperature_solar:
      name: "Solar"
    temperature_influx:
      name: "Zulauf"
    temperature_reflux:
      name: "Ruecklauf"
    binary_sensor:
      name: "Pumpe Status"

binary_sensor:


# Enable Home Assistant API
api:
  encryption:
    key: "zzWiXRueaWxkV3hUGfHXX2de3WcxYpXe1Iyxd2qNEEc="

ota:
  password: "039e3eb6eed06cc44165c38347b7683e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gpiotest Fallback Hotspot"
    password: "rMVepOhRBZCY"


    