
esphome:
  name: boilercontrol2
  friendly_name: Boilercontrol2
  build_path: /homeassistant/esphome/tmp
  platformio_options:
    board_build.flash_mode: dio
#  includes:
#    - custom_components/boilercontrol/boilercontrol.h
#    - custom_components/boilercontrol/boilercontrol.cpp

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

 
#external_components:
# - source:
#      type: local
#      path: ./boilercontrol

    

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG


external_components:
  - source:
      type: local
      path: my_components
    components: [boilercontrol]


sensor:
  - platform: boilercontrol
    temperature_boiler:
      name: "Boiler"
    temperature_solar:
      name: "Solar"
    temperature_influx:
      name: "Zulauf"
    temperature_reflux:
      name: "Ruecklauf"
    binary_sensor:
      name: "Pumpe Status"

binary_sensor:


# Enable Home Assistant API
api:
  encryption:
    key: "zzWiXRueaWxkV3hUGfHXX2de3WcxYpXe1Iyxd2qNEEc="

ota:
  password: "039e3eb6eed06cc44165c38347b7683e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gpiotest Fallback Hotspot"
    password: "rMVepOhRBZCY"

captive_portal:
    